# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ATSAppStructure' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ATSAppStructure

  pod 'Masonry', '~> 1.0.2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'FMDB', '~> 2.6.2'		
  target 'ATSAppStructureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ATSAppStructureUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
